function(template_filter_string)
  if(ARGV0 STREQUAL "RAW")
    set(tag "")
    while(IT MATCHES "\\)(${tag}_*)\"")
      set(tag "${CMAKE_MATCH_1}_")
    endwhile()
    set(IT "R\"${tag}(${IT})${tag}\"" PARENT_SCOPE)
    return()
  else()
    string_escape("${IT}" IT)
  endif()
endfunction()

function(template_filter_set)
  set(IT "${ARGN}" PARENT_SCOPE)
endfunction()

macro(template_filter_if_else then otherwise)
  if(${IT})
    set(IT "${then}")
  else()
    set(IT "${otherwise}")
  endif()
endmacro()
